table FactFlights
	lineageTag: 9cc90b1b-907e-4837-91fd-fe43c2cdffa1

	column FlightKey
		dataType: int64
		isHidden
		lineageTag: b9995338-ade3-4dce-9616-ce5697d17991
		summarizeBy: none
		sourceColumn: FlightKey

	column DateKey
		dataType: int64
		isHidden
		lineageTag: 00926f69-3ea8-425d-b37f-ab5926ec4bd0
		summarizeBy: none
		sourceColumn: DateKey

	column AirlineKey
		dataType: int64
		isHidden
		lineageTag: 88355674-cc88-47ad-870a-03d40afed5e6
		summarizeBy: none
		sourceColumn: AirlineKey

	column OriginAirportKey
		dataType: int64
		isHidden
		lineageTag: 1afebe3f-45a5-403e-aebb-427a30a28ddb
		summarizeBy: none
		sourceColumn: OriginAirportKey

	column DestAirportKey
		dataType: int64
		isHidden
		lineageTag: fac32474-a440-4861-93db-940b1238e5d9
		summarizeBy: none
		sourceColumn: DestAirportKey

	column RouteKey
		dataType: int64
		isHidden
		lineageTag: 46465057-63f3-4ff5-8901-0e0fa7a6bac5
		summarizeBy: none
		sourceColumn: RouteKey

	column FlightNumber
		dataType: int64
		lineageTag: fb5d1963-ec31-4c4e-b0a8-d153e37c4122
		summarizeBy: none
		sourceColumn: FlightNumber

	column TailNumber
		dataType: string
		lineageTag: 3879912e-16ae-4782-b13f-c1f439acef82
		summarizeBy: none
		sourceColumn: TailNumber

	column CRSDepTime
		dataType: int64
		lineageTag: 000c1199-d6fc-4ffd-a772-c099a85245b3
		summarizeBy: none
		sourceColumn: CRSDepTime

	column DepTime
		dataType: double
		lineageTag: e10ffdb5-e5d6-48f0-81b7-08c5dd9eb44f
		summarizeBy: none
		sourceColumn: DepTime

	column DepDelay
		dataType: double
		lineageTag: 9ba85ae8-2851-45b8-9203-2e973791d8b3
		summarizeBy: sum
		sourceColumn: DepDelay

	column DepDelayMinutes
		dataType: double
		lineageTag: 1569feaa-05a2-4947-a47f-4a2c4a35ec31
		summarizeBy: sum
		sourceColumn: DepDelayMinutes

	column CRSArrTime
		dataType: int64
		lineageTag: dbc42bc6-d404-4b68-8af5-198e04fd44f7
		summarizeBy: none
		sourceColumn: CRSArrTime

	column ArrTime
		dataType: double
		lineageTag: 0506c564-ce95-463c-9e3d-6cac90089d95
		summarizeBy: none
		sourceColumn: ArrTime

	column ArrDelay
		dataType: double
		lineageTag: 422fee77-5708-4362-be72-815c6f8afbfc
		summarizeBy: sum
		sourceColumn: ArrDelay

	column ArrDelayMinutes
		dataType: double
		lineageTag: 8629d332-2f63-4ce9-b289-59deb2f9be46
		summarizeBy: sum
		sourceColumn: ArrDelayMinutes

	column Cancelled
		dataType: int64
		lineageTag: 34adeb9b-27b7-418e-a3fd-e81b7c012d94
		summarizeBy: sum
		sourceColumn: Cancelled

	column CancellationCode
		dataType: string
		lineageTag: df26ab63-6976-4e32-9e0a-9f4131142ca4
		summarizeBy: none
		sourceColumn: CancellationCode

	column Diverted
		dataType: int64
		lineageTag: 4841164e-c24c-4cd2-b888-f7513ca5e42b
		summarizeBy: sum
		sourceColumn: Diverted

	column Distance
		dataType: double
		lineageTag: 35b58807-b1fa-4381-ae4c-a899bc716495
		summarizeBy: sum
		sourceColumn: Distance

	column AirTime
		dataType: double
		lineageTag: bb7f46e8-8232-4335-a065-fd7c6800e6ae
		summarizeBy: sum
		sourceColumn: AirTime

	column CRSElapsedTime
		dataType: double
		lineageTag: 5815cea9-27ca-4a00-89bc-ad7797f576e0
		summarizeBy: none
		sourceColumn: CRSElapsedTime

	column ActualElapsedTime
		dataType: double
		lineageTag: 12cb3164-ffac-4c70-acb6-f8c37db4cbd4
		summarizeBy: none
		sourceColumn: ActualElapsedTime

	column CarrierDelay
		dataType: double
		lineageTag: e41f4e33-56cf-4428-82b9-c1ca220aebc6
		summarizeBy: sum
		sourceColumn: CarrierDelay

	column WeatherDelay
		dataType: double
		lineageTag: 947c449d-f0ca-47db-b3f5-ffbf4a6f554d
		summarizeBy: sum
		sourceColumn: WeatherDelay

	column NASDelay
		dataType: double
		lineageTag: 4cbfa554-a259-4451-a04e-f85cf6cca6ab
		summarizeBy: sum
		sourceColumn: NASDelay

	column SecurityDelay
		dataType: double
		lineageTag: e31656be-f5e2-42d5-a4ae-4361ebf89527
		summarizeBy: sum
		sourceColumn: SecurityDelay

	column LateAircraftDelay
		dataType: double
		lineageTag: 1f9ef8c8-6f19-4398-9e71-beb964bef4b7
		summarizeBy: sum
		sourceColumn: LateAircraftDelay

	column DepTimeBlk
		dataType: string
		lineageTag: f400941c-a905-4c0a-84bd-3d6ce013f155
		summarizeBy: none
		sourceColumn: DepTimeBlk

	column IsDelayedDep
		dataType: int64
		lineageTag: 3953a1cc-8365-4a99-91a4-f78048b307ab
		summarizeBy: sum
		sourceColumn: IsDelayedDep

	column IsDelayedArr
		dataType: int64
		lineageTag: ece24c75-444f-4a58-a0e6-81f908a50f73
		summarizeBy: sum
		sourceColumn: IsDelayedArr

	column IsOnTimeArr
		dataType: int64
		lineageTag: 865be3ee-5e27-4af6-94ec-94afc84ac2e6
		summarizeBy: sum
		sourceColumn: IsOnTimeArr

	partition FactFlights = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pDataFolder & "\\fact_flights.csv"), [Delimiter=",", Columns=32, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(#"Promoted Headers", {{"FlightKey", Int64.Type}, {"DateKey", Int64.Type}, {"AirlineKey", Int64.Type}, {"OriginAirportKey", Int64.Type}, {"DestAirportKey", Int64.Type}, {"RouteKey", Int64.Type}, {"FlightNumber", Int64.Type}, {"TailNumber", type text}, {"CRSDepTime", Int64.Type}, {"DepTime", type number}, {"DepDelay", type number}, {"DepDelayMinutes", type number}, {"CRSArrTime", Int64.Type}, {"ArrTime", type number}, {"ArrDelay", type number}, {"ArrDelayMinutes", type number}, {"Cancelled", Int64.Type}, {"CancellationCode", type text}, {"Diverted", Int64.Type}, {"Distance", type number}, {"AirTime", type number}, {"CRSElapsedTime", type number}, {"ActualElapsedTime", type number}, {"CarrierDelay", type number}, {"WeatherDelay", type number}, {"NASDelay", type number}, {"SecurityDelay", type number}, {"LateAircraftDelay", type number}, {"DepTimeBlk", type text}, {"IsDelayedDep", Int64.Type}, {"IsDelayedArr", Int64.Type}, {"IsOnTimeArr", Int64.Type}})
				in
				    Typed

